"""Decode the dormant page-3F LCD and keypad manufacturing diagnostic."""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256

from ti84re.rom.image import RomImage, RomLocation
from ti84re.trace.resolve import KEY_NAMES

BOOT_PAGE = 0x3F
DIAGNOSTIC_START = 0x4658
DIAGNOSTIC_END = 0x47EF
KEY_TABLE_START = 0x478D
KEY_TABLE_ENTRIES = 49
DIAGNOSTIC_SHA256 = "17eb8152b31caa5f39532fbaf179c0806948f50729779f4c62e40e67696b38fb"
KEY_TABLE_SHA256 = "909630db1b850f4ae09171bfca52dfcb816e375a6c7ffc4c3dce1cf9d873e411"
UNREACHABLE_GUARD = bytes.fromhex("AFD305FE092841C31045")

VISIBLE_ROWS = 64
VISIBLE_COLUMNS = 12
ROW_COMMAND = 0x80
COLUMN_COMMAND = 0x20


@dataclass(frozen=True)
class LcdWrite:
    """One controller write generated by a decoded diagnostic helper."""

    port: int
    value: int
    kind: str


@dataclass(frozen=True)
class LcdPatternStage:
    """One key-advanced full-screen LCD test pattern."""

    name: str
    even_row: int
    odd_row: int
    bordered: bool
    command_writes: int
    data_writes: int
    screen_sha256: str


@dataclass(frozen=True)
class ContrastStep:
    """One raw diagnostic counter and its emitted controller command."""

    counter: int
    command: int
    controller_level: int


@dataclass(frozen=True)
class KeyPrompt:
    """One expected scan code and decimal label shown by the diagnostic."""

    index: int
    scan_code: int
    key_name: str
    display_value: int


@dataclass(frozen=True)
class LcdDiagnosticReachability:
    """The sole ROM predecessor and its constant branch result."""

    branch_location: RomLocation
    target: RomLocation
    a_before_compare: int
    compared_value: int
    zero_flag: bool
    reachable: bool


def _byte(value: int) -> int:
    if not 0 <= value <= 0xFF:
        raise ValueError("LCD diagnostic values must be bytes")
    return value


def lcd_fill_writes(even_row: int, odd_row: int) -> tuple[LcdWrite, ...]:
    """Expand ``3F:46EF`` for all 12 visible columns and 64 rows."""

    even_row = _byte(even_row)
    odd_row = _byte(odd_row)
    writes: list[LcdWrite] = []
    for column in range(COLUMN_COMMAND, COLUMN_COMMAND + VISIBLE_COLUMNS):
        writes.extend(
            (
                LcdWrite(0x10, ROW_COMMAND, "row-command"),
                LcdWrite(0x10, column, "column-command"),
            )
        )
        for row in range(VISIBLE_ROWS):
            writes.append(
                LcdWrite(
                    0x11,
                    even_row if row % 2 == 0 else odd_row,
                    "data",
                )
            )
    return tuple(writes)


def lcd_line_writes(row: int, value: int) -> tuple[LcdWrite, ...]:
    """Expand ``3F:472E`` across the 12 visible byte columns."""

    row = _byte(row)
    value = _byte(value)
    if not ROW_COMMAND <= row < ROW_COMMAND + VISIBLE_ROWS:
        raise ValueError("LCD diagnostic row command must be between 0x80 and 0xBF")
    writes: list[LcdWrite] = []
    for column in range(COLUMN_COMMAND, COLUMN_COMMAND + VISIBLE_COLUMNS):
        writes.extend(
            (
                LcdWrite(0x10, row, "row-command"),
                LcdWrite(0x10, column, "column-command"),
                LcdWrite(0x11, value, "data"),
            )
        )
    return tuple(writes)


def visible_pattern(even_row: int, odd_row: int, *, bordered: bool = False) -> bytes:
    """Return row-major visible bytes after one decoded pattern stage."""

    even_row = _byte(even_row)
    odd_row = _byte(odd_row)
    rows = []
    for row in range(VISIBLE_ROWS):
        value = even_row if row % 2 == 0 else odd_row
        if bordered and row in (0, VISIBLE_ROWS - 1):
            value = 0xFF
        rows.append(bytes((value,)) * VISIBLE_COLUMNS)
    return b"".join(rows)


def fnv1a64(data: bytes) -> int:
    """Return the 64-bit FNV-1a digest used by compact native probes."""

    value = 0xCBF29CE484222325
    for byte in data:
        value ^= byte
        value = (value * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return value


def lcd_pattern_stages() -> tuple[LcdPatternStage, ...]:
    """Return the six key-advanced screens emitted by ``3F:4658``."""

    definitions = (
        ("0x81 field with black top and bottom rows", 0x81, 0x81, True),
        ("all black", 0xFF, 0xFF, False),
        ("all white", 0x00, 0x00, False),
        ("alternating 0x55 and 0xAA rows", 0x55, 0xAA, False),
        ("alternating 0x00 and 0xFF rows", 0x00, 0xFF, False),
        ("0xAA vertical stripes", 0xAA, 0xAA, False),
    )
    stages: list[LcdPatternStage] = []
    for name, even_row, odd_row, bordered in definitions:
        fill = lcd_fill_writes(even_row, odd_row)
        line = (
            (*lcd_line_writes(0x80, 0xFF), *lcd_line_writes(0xBF, 0xFF))
            if bordered
            else ()
        )
        writes = (*fill, *line)
        screen = visible_pattern(even_row, odd_row, bordered=bordered)
        stages.append(
            LcdPatternStage(
                name=name,
                even_row=even_row,
                odd_row=odd_row,
                bordered=bordered,
                command_writes=sum(write.port == 0x10 for write in writes),
                data_writes=sum(write.port == 0x11 for write in writes),
                screen_sha256=sha256(screen).hexdigest(),
            )
        )
    return tuple(stages)


def contrast_sweep() -> tuple[ContrastStep, ...]:
    """Decode counters ``0x27`` down to ``0x01`` through ``3F:74F8``."""

    return tuple(
        ContrastStep(
            counter=counter,
            command=((counter + 0x18) & 0xFF) | 0xC0,
            controller_level=(counter + 0x18) & 0x3F,
        )
        for counter in range(0x27, 0, -1)
    )


def key_prompts(rom: RomImage) -> tuple[KeyPrompt, ...]:
    """Decode the 49 scan-code/display-number pairs at ``3F:478D``."""

    data = rom.bytes_at(
        BOOT_PAGE,
        KEY_TABLE_START,
        KEY_TABLE_ENTRIES * 2,
    )
    return tuple(
        KeyPrompt(
            index=index,
            scan_code=data[index * 2],
            key_name=KEY_NAMES.get(data[index * 2], "?"),
            display_value=data[index * 2 + 1],
        )
        for index in range(KEY_TABLE_ENTRIES)
    )


def lcd_diagnostic_reachability(rom: RomImage) -> LcdDiagnosticReachability:
    """Verify and evaluate the only branch into ``3F:4658``."""

    guard = rom.bytes_at(BOOT_PAGE, 0x4610, len(UNREACHABLE_GUARD))
    if guard != UNREACHABLE_GUARD:
        raise ValueError(
            f"unrecognized LCD-diagnostic predecessor at 3F:4610: {guard.hex()}"
        )
    return LcdDiagnosticReachability(
        branch_location=RomLocation(BOOT_PAGE, 0x4615),
        target=RomLocation(BOOT_PAGE, DIAGNOSTIC_START),
        a_before_compare=0,
        compared_value=9,
        zero_flag=False,
        reachable=False,
    )


def validate_lcd_diagnostic_rom(rom: RomImage) -> tuple[str, ...]:
    """Hash-check the code/table region and its unreachable predecessor."""

    errors: list[str] = []
    diagnostic = rom.bytes_at(
        BOOT_PAGE,
        DIAGNOSTIC_START,
        DIAGNOSTIC_END - DIAGNOSTIC_START,
    )
    table = rom.bytes_at(
        BOOT_PAGE,
        KEY_TABLE_START,
        KEY_TABLE_ENTRIES * 2,
    )
    actual_diagnostic = sha256(diagnostic).hexdigest()
    actual_table = sha256(table).hexdigest()
    if actual_diagnostic != DIAGNOSTIC_SHA256:
        errors.append(
            f"3F:{DIAGNOSTIC_START:04X}-3F:{DIAGNOSTIC_END - 1:04X} "
            f"SHA-256 {actual_diagnostic} != {DIAGNOSTIC_SHA256}"
        )
    if actual_table != KEY_TABLE_SHA256:
        errors.append(
            f"3F:{KEY_TABLE_START:04X} key-table SHA-256 "
            f"{actual_table} != {KEY_TABLE_SHA256}"
        )
    try:
        lcd_diagnostic_reachability(rom)
    except ValueError as error:
        errors.append(str(error))
    return tuple(errors)


def lcd_diagnostic_summary(rom: RomImage) -> dict[str, object]:
    """Return one JSON-ready static diagnostic report."""

    stages = lcd_pattern_stages()
    contrast = contrast_sweep()
    prompts = key_prompts(rom)
    reachability = lcd_diagnostic_reachability(rom)
    errors = validate_lcd_diagnostic_rom(rom)
    return {
        "valid": not errors,
        "errors": list(errors),
        "reachability": {
            "branch_location": str(reachability.branch_location),
            "target": str(reachability.target),
            "a_before_compare": reachability.a_before_compare,
            "compared_value": reachability.compared_value,
            "zero_flag": reachability.zero_flag,
            "reachable": reachability.reachable,
        },
        "patterns": [stage.__dict__ for stage in stages],
        "pattern_checkpoints": len(stages),
        "pattern_command_writes": sum(stage.command_writes for stage in stages),
        "pattern_data_writes": sum(stage.data_writes for stage in stages),
        "contrast": [step.__dict__ for step in contrast],
        "contrast_checkpoints": len(contrast),
        "keys": [prompt.__dict__ for prompt in prompts],
        "key_count": len(prompts),
    }
