#!/usr/bin/env python3
"""Validate ignored retail artifacts and assemble the local complete ROM.

Inputs are copyrighted and intentionally gitignored:
  tools/roms/ti84plus_patched.rom
  tools/roms/D84PBE1.8Xv
  tools/roms/D84PBE2.8Xv

D84PBE1 is the retail boot page, installed as page 0x3F. D84PBE2 is the
USB/OS-receive boot support page, installed as page 0x2F.
"""
from __future__ import annotations

import argparse
from dataclasses import asdict
import json
from pathlib import Path
import os

from rom_assembly import RomAssemblyError, assemble_complete_rom


HERE = Path(__file__).resolve().parent
ROMS = HERE / "roms"
BASE_ROM = ROMS / "ti84plus_patched.rom"
BOOT_PAGE_APPVAR = ROMS / "D84PBE1.8Xv"
USB_PAGE_APPVAR = ROMS / "D84PBE2.8Xv"
OUT_ROM = ROMS / "ti84plus_2.55mp_complete.rom"
ROM_LINK = HERE / "rom.bin"
PAGE0 = HERE / "ti84_page00.bin"

def relpath(path: Path, start: Path) -> str:
    return os.path.relpath(path, start)


def install_file(path: Path, data: bytes, *, force: bool) -> str:
    """Create, retain, or explicitly replace one generated byte file."""

    if path.exists() or path.is_symlink():
        if path.is_file() and not path.is_symlink() and path.read_bytes() == data:
            return "unchanged"
        if not force:
            raise RomAssemblyError(
                f"refusing to replace existing {path}; use --force"
            )
        if path.is_dir() and not path.is_symlink():
            raise RomAssemblyError(f"refusing to replace directory {path}")
        path.unlink()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return "written"


def install_link(path: Path, target: Path, *, force: bool) -> str:
    """Create or retain the generated ROM symlink without broad deletion."""

    desired = relpath(target, path.parent)
    if path.is_symlink() and os.readlink(path) == desired:
        return "unchanged"
    if path.exists() or path.is_symlink():
        if not force:
            raise RomAssemblyError(
                f"refusing to replace existing {path}; use --force"
            )
        if path.is_dir() and not path.is_symlink():
            raise RomAssemblyError(f"refusing to replace directory {path}")
        path.unlink()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.symlink_to(desired)
    return "written"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-rom", type=Path, default=BASE_ROM)
    parser.add_argument("--boot-appvar", type=Path, default=BOOT_PAGE_APPVAR)
    parser.add_argument("--usb-appvar", type=Path, default=USB_PAGE_APPVAR)
    parser.add_argument("--output-rom", type=Path, default=OUT_ROM)
    parser.add_argument("--page0", type=Path, default=PAGE0)
    parser.add_argument("--rom-link", type=Path, default=ROM_LINK)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    inputs = {
        "D84PBE1.8Xv": args.boot_appvar,
        "D84PBE2.8Xv": args.usb_appvar,
    }
    try:
        missing = [args.base_rom, *(path for path in inputs.values())]
        missing = [path for path in missing if not path.is_file()]
        if missing:
            raise RomAssemblyError(
                "missing local ROM artifact(s): "
                + ", ".join(str(path) for path in missing)
            )
        assembly = assemble_complete_rom(
            args.base_rom.read_bytes(),
            {name: path.read_bytes() for name, path in inputs.items()},
        )
        if args.check:
            actions = {
                "output_rom": "check-only",
                "page0": "check-only",
                "rom_link": "check-only",
            }
        else:
            actions = {
                "output_rom": install_file(
                    args.output_rom, assembly.image, force=args.force
                ),
                "page0": install_file(args.page0, assembly.page0, force=args.force),
                "rom_link": install_link(
                    args.rom_link, args.output_rom, force=args.force
                ),
            }
    except (OSError, RomAssemblyError) as error:
        parser.error(str(error))

    report = {
        "base_rom": str(args.base_rom),
        "base_sha256": assembly.base_sha256,
        "inputs": {name: str(path) for name, path in inputs.items()},
        "retail_pages": [asdict(patch) for patch in assembly.patches],
        "output_rom": str(args.output_rom),
        "output_sha256": assembly.output_sha256,
        "page0": str(args.page0),
        "rom_link": str(args.rom_link),
        "actions": actions,
    }
    if args.json:
        print(json.dumps(report, indent=2))
        return
    print(f"base SHA-256: {assembly.base_sha256}")
    for patch in assembly.patches:
        print(
            f"page {patch.page:02X}: {patch.filename} "
            f"changed={patch.changed_bytes} page_sha256={patch.page_sha256}"
        )
    print(f"output SHA-256: {assembly.output_sha256}")
    for label, action in actions.items():
        print(f"{label}: {action}")


if __name__ == "__main__":
    main()
