#!/usr/bin/env python3
"""Regenerate docs/token-tables.md from the TI-Toolkit/tokens sheet.

The 2-byte token names come from https://github.com/TI-Toolkit/tokens (8X.xml).
We keep only tokens present on the monochrome TI-84+ (<= OS 2.55MP) — the
TI-84+CSE / TI-84+CE color/Python-era 2-byte tokens are excluded.

Usage:
    python3 tools/gen-token-tables.py            # fetch 8X.xml from GitHub
    python3 tools/gen-token-tables.py 8X.xml     # use a local copy
"""
import sys, os, urllib.request
import xml.etree.ElementTree as ET

URL = "https://raw.githubusercontent.com/TI-Toolkit/tokens/main/8X.xml"
INCLUDE = {"TI-82", "TI-83", "TI-83+", "TI-84+"}  # exclude TI-84+CSE / TI-84+CE
ORDER = ["$5C", "$5D", "$5E", "$60", "$61", "$62", "$63", "$7E", "$AA", "$BB", "$EF"]
DESC = {
    "$5C": ("Matrix names", "`[A]`–`[J]`"),
    "$5D": ("List names", "built-in `L₁`–`L₆`"),
    "$5E": ("Equation variables", "Y= functions, parametric, polar, sequence"),
    "$60": ("Pictures", "`Pic1`–`Pic0`"),
    "$61": ("Graph databases", "`GDB1`–`GDB0`"),
    "$62": ("Statistics / regression / output variables", ""),
    "$63": ("Window & system variables", ""),
    "$7E": ("Graph-format & mode tokens", ""),
    "$AA": ("String variables", "`Str1`–`Str0`"),
    "$BB": ("Extended command page (2-byte commands)", ""),
    "$EF": ("TI-84+-era extended tokens", "date/time, clock, GarbageCollect…"),
}
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "docs", "token-tables.md")


def en_disp_since(tok):
    v = tok.find("version")
    if v is None:
        return None, None
    disp = None
    for lang in v.findall("lang"):
        if lang.get("code") == "en":
            disp = lang.get("display")
            break
    if disp is None:
        l = v.find("lang")
        disp = l.get("display") if l is not None else None
    s = v.find("since")
    m = s.find("model").text if s is not None and s.find("model") is not None else ""
    return disp, m


def main():
    if len(sys.argv) > 1:
        data = open(sys.argv[1], "rb").read()
    else:
        data = urllib.request.urlopen(URL, timeout=30).read()
    root = ET.fromstring(data)
    groups = {g.get("value"): g for g in root.findall("two-byte")}

    sections, total = [], 0
    for lead in ORDER:
        g = groups[lead]
        name, extra = DESC[lead]
        rows = []
        for k in g.findall("token"):
            disp, m = en_disp_since(k)
            if m not in INCLUDE or disp is None:
                continue
            rows.append((k.get("value")[1:], disp.replace("|", "\\|"), m))
        total += len(rows)
        head = f"## `{lead[1:]}` — {name}" + (f"  ({extra})" if extra else "")
        body = [head, "", f"*{len(rows)} tokens on the 84+ (2.55MP).*  Second byte → token:", "",
                "| 2nd | Token | Since |", "|-----|-------|-------|"]
        body += [f"| `{v}` | `{d}` | {m} |" for v, d, m in rows]
        sections.append("\n".join(body))

    header = f"""# 2-Byte Token Tables

The second-byte tables for every **2-byte token** on the TI-84 Plus (OS 2.55MP). The tokenizer detects a 2-byte lead via `_IsA2ByteTok` (`00:1FE8`) — see [Tokenizer & TI-BASIC](07-tokenizer-basic.md) — then the **second byte** indexes the group below.

Names are sourced from the **[TI-Toolkit/tokens](https://github.com/TI-Toolkit/tokens)** sheet (`8X.xml`) and filtered to tokens that exist on the **monochrome 84+ (≤ 2.55MP)**: the `TI-84+CSE`/`TI-84+CE` color/Python-era 2-byte tokens are **excluded**. The `Since` column is the model that introduced each token. Token text is the English *display* form (the source also carries an ASCII-`accessible` spelling, e.g. `>DMS` for `►DMS`).

{total} two-byte tokens across {len(ORDER)} lead bytes. (Single-byte tokens are modeled by the `TIToken` enum — see [07](07-tokenizer-basic.md).)

This file is generated by `tools/gen-token-tables.py`; edit that, not this.

---
"""
    with open(OUT, "w") as f:
        f.write(header + "\n" + "\n\n".join(sections) + "\n")
    print(f"wrote {OUT}: {total} two-byte tokens")


if __name__ == "__main__":
    main()
